<?php
declare(strict_types=1);

namespace App\Presenters;
use App\Model\Play;
use App\Model\Show;
use Nette\Application\AbortException;
use Nette\Database\Connection;
use ReflectionException as ReflectionExceptionAlias;

class PlayDetailPresenter extends BasePresenter {
    /** @var Connection @inject */
    public Connection $connection;
    private Show $show;


    protected function startup() :void {
        parent::startup(); // TODO: Change the autogenerated stub
        $this->show = new Show($this->connection);
    }

    /**
     * @param int $idPlay
     * @throws ReflectionExceptionAlias
     */
    public function renderDefault (int $idPlay) : void {
        $play = new Play($this->connection);
        $this->template->playDetail =$play->getPlayDetail($idPlay);
        $showResponse = $this->show->getShowsForPlay($idPlay);
        if(empty($showResponse)){
            $this->template->answear = 'K hre neexistuje zatiaľ žiadne predstavenie';
        } else {
            $this->template->showResponse = $showResponse;
        }
    }

    /**
     * @param $id
     * @throws AbortException
     */
    public function handleMod($id): void {
            $this->redirect('ModifyPlay:Default', (int)$id);
    }

    /**
     * @param $id
     * @param $usage
     * @throws AbortException
     */
    public function handleDelete ($id, $usage): void {
            $this->show->removeShow((int)$id, (int)$usage);
            $this->flashMessage('Predstavenie úspešne vymazané ', 'info');
       //     $this->redirect(':EmployeeHomepage:default');
    }

}